# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_logs\admin_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import qtawesome
import img
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class AdminMainUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 694)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.frame = QtWidgets.QFrame(self.main_widget)
        self.frame.setGeometry(QtCore.QRect(70, 40, 300, 600))
        self.frame.setMinimumSize(QtCore.QSize(300, 600))
        self.frame.setStyleSheet("#frame{border: 1px solid #8f8f91; \n"
                                 "background:#ffffff;\n"
                                 "                border-top-left-radius:7px;\n"
                                 "                border-top-right-radius:7px;\n"
                                 "                border-bottom-left-radius:7px;\n"
                                 "                border-bottom-right-radius:7px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.close_button = QtWidgets.QPushButton(self.frame_2)
        self.close_button.setGeometry(QtCore.QRect(230, 10, 38, 38))
        self.close_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_button.setStyleSheet("QPushButton{\n"
                                        "                background-color: transparent; \n"
                                        "                border-radius:7px;\n"
                                        "  border: 2px solid #a0a6b1;}\n"
                                        "            QPushButton:hover{\n"
                                        "               padding-top:5px;\n"
                                        "padding-left:5px;\n"
                                        "}")
        self.close_button.setText("")
        icon_close = qtawesome.icon('fa.times', color='grey')
        self.close_button.setIcon(icon_close)
        self.close_button.setIconSize(QtCore.QSize(30, 30))  # 根据需要调整图标大小
        self.close_button.setObjectName("close_button")
        self.minimize_button = QtWidgets.QPushButton(self.frame_2)
        self.minimize_button.setGeometry(QtCore.QRect(180, 10, 38, 38))
        self.minimize_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize_button.setStyleSheet("QPushButton{\n"
                                           "                background-color: transparent; \n"
                                           "                border-radius:7px;\n"
                                           "  border: 2px solid #a0a6b1;}\n"
                                           "            QPushButton:hover{\n"
                                           "               padding-top:5px;\n"
                                           "padding-left:5px;\n"
                                           "}")
        self.minimize_button.setText("")
        self.minimize_button.setObjectName("minimize_button")
        icon_minimize = qtawesome.icon('fa.minus', color='grey')
        self.minimize_button.setIcon(icon_minimize)
        self.minimize_button.setIconSize(QtCore.QSize(30, 30))  # 根据需要调整图标大小
        self.minimize_button.setObjectName("minimize_button")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(33, 0, 33, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("QPushButton{\n"
                                   "                border:none;\n"
                                   "                color:#737b89;\n"
                                   "                padding-left:5px;\n"
                                   "                height:35px;\n"
                                   "                font-size:18px;\n"
                                   "                font-weight: 600;\n"
                                   "                padding-right:10px;\n"
                                   "font-family:\"微软雅黑\"}\n"
                                   "QPushButton:hover{ \n"
                                   "                color:white;\n"
                                   "                border:2px solid #F0F7F4;\n"
                                   "                border-radius:15px;\n"
                                   "                background:#4d5353;}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setEnabled(False)
        self.pushButton.setStyleSheet("color:#787f8d;\n"
                                      "border:none;\n"
                                      "                border-bottom:1px solid #787f8d;\n"
                                      "                font-size:20px;\n"
                                      "                font-weight:700;\n"
                                      "font-family:\"微软雅黑\"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.login_button = QtWidgets.QPushButton(self.frame_4)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setObjectName("login_button")
        self.verticalLayout_3.addWidget(self.login_button)
        self.unlock_button = QtWidgets.QPushButton(self.frame_4)
        self.unlock_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.unlock_button.setObjectName("unlock_button")
        self.verticalLayout_3.addWidget(self.unlock_button)
        self.delete_button = QtWidgets.QPushButton(self.frame_4)
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout_3.addWidget(self.delete_button)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setStyleSheet("color:#787f8d;\n"
                                        "border:none;\n"
                                        "                border-bottom:1px solid #787f8d;\n"
                                        "                font-size:20px;\n"
                                        "                font-weight:700;\n"
                                        "font-family:\"微软雅黑\"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.query_records_button = QtWidgets.QPushButton(self.frame_4)
        self.query_records_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.query_records_button.setObjectName("query_records_button")
        self.verticalLayout_3.addWidget(self.query_records_button)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setStyleSheet("color:#787f8d;\n"
                                        "border:none;\n"
                                        "                border-bottom:1px solid #787f8d;\n"
                                        "                font-size:20px;\n"
                                        "                font-weight:700;\n"
                                        "font-family:\"微软雅黑\"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.setting_button = QtWidgets.QPushButton(self.frame_4)
        self.setting_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_button.setObjectName("setting_button")
        self.verticalLayout_3.addWidget(self.setting_button)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.main_widget)
        # 设置整体样式
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # 隐藏边框
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)

        MainWindow.setWindowTitle("管理员界面")  # 设置标题
        MainWindow.setWindowIcon(QIcon(':/icons/images/logo.jpg'))  # 设置logo
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ADMIN"))
        self.login_button.setText(_translate("MainWindow", "管理员登录"))
        self.login_button.setIcon(qtawesome.icon('fa5s.user-alt', color='#737b89'))

        self.unlock_button.setText(_translate("MainWindow", "用户信息修改"))
        self.unlock_button.setIcon(qtawesome.icon('fa5s.user-alt', color='#737b89'))

        self.delete_button.setText(_translate("MainWindow", "用户注销"))
        self.delete_button.setIcon(qtawesome.icon('fa5s.user-alt', color='#737b89'))
        self.pushButton_2.setText(_translate("MainWindow", "HISTORY"))
        self.query_records_button.setText(_translate("MainWindow", "历史记录"))
        self.query_records_button.setIcon(qtawesome.icon('fa5s.history', color='#737b89'))

        self.pushButton_3.setText(_translate("MainWindow", "SETTING"))
        self.setting_button.setText(_translate("MainWindow", "系统设置"))
        self.setting_button.setIcon(qtawesome.icon('fa.cog', color='#737b89'))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    widgets = QtWidgets.QMainWindow()
    ui = AdminMainUi()
    ui.setupUi(widgets)
    widgets.show()
    sys.exit(app.exec_())
