# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import qtawesome
import img
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QPoint
from PyQt5.QtGui import QIcon, QCursor
from PyQt5.QtWidgets import QApplication


class UserMainUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1360, 900)
        # 获取主屏幕
        screen = QApplication.primaryScreen()

        # 获取屏幕大小
        screen_size = screen.size()

        # 计算窗口在屏幕上的位置，使其居中
        width, height = MainWindow.width(), MainWindow.height()
        x = (screen_size.width() - width) // 2
        y = (screen_size.height() - height) // 2

        # 移动窗口到屏幕中央
        MainWindow.move(QPoint(x, y))
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setMinimumSize(QtCore.QSize(1300, 900))
        self.main_widget.setObjectName("main_widget")
        # 设置主窗口的中央部件
        MainWindow.setCentralWidget(self.main_widget)

        # 创建布局管理器
        self.main_layout_manager = QtWidgets.QVBoxLayout(self.main_widget)
        self.main_layout_manager.setContentsMargins(0, 0, 0, 0)
        self.main_layout_manager.setSpacing(0)
        # 创建 main_layout，它实际上是一个 QFrame
        self.main_layout = QtWidgets.QFrame(self.main_widget)
        self.main_layout.setMinimumSize(QtCore.QSize(1200, 800))
        self.main_layout.setAutoFillBackground(False)
        self.main_layout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_layout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_layout.setObjectName("main_layout")
        # 将 main_layout 添加到布局管理器中
        self.main_layout_manager.addWidget(self.main_layout)
        # 其他
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_layout)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_widget = QtWidgets.QFrame(self.main_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_widget.sizePolicy().hasHeightForWidth())
        self.left_widget.setSizePolicy(sizePolicy)
        self.left_widget.setStyleSheet("#left_widget{\n"
                                       "                background:#f0f3f6;\n"
                                       "                border-top-left-radius:5px;\n"
                                       "                border-bottom-left-radius:5px;}  ")
        self.left_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_top_frame = QtWidgets.QFrame(self.left_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.left_top_frame.sizePolicy().hasHeightForWidth())
        self.left_top_frame.setSizePolicy(sizePolicy)
        self.left_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_top_frame.setObjectName("left_top_frame")
        self.name_label = QtWidgets.QLabel(self.left_top_frame)
        self.name_label.setGeometry(QtCore.QRect(80, 20, 151, 51))
        self.name_label.setStyleSheet("color:#1a1a23;\n"
                                      "                border:none;\n"
                                      "                font-size:20px;\n"
                                      "                font-family: Helvetica, \'Hiragino Sans GB\', \'Microsoft Yahei\', \'微软雅黑\', Arial, sans-serif;")
        self.name_label.setObjectName("name_label")
        self.label = QtWidgets.QLabel(self.left_top_frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/images/logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.left_top_frame)
        self.pushButton.setGeometry(QtCore.QRect(230, 30, 41, 31))
        self.pushButton.setStyleSheet("font-size:12px;\n"
                                      "background-color: transparent;  \n"
                                      "  \n"
                                      "  border-radius: 9px; \n"
                                      "  border: 2px solid #a0a6b1;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.left_top_frame)
        self.left_under_frame = QtWidgets.QFrame(self.left_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(self.left_under_frame.sizePolicy().hasHeightForWidth())
        self.left_under_frame.setSizePolicy(sizePolicy)
        self.left_under_frame.setStyleSheet("QPushButton{\n"
                                            "                border:none;\n"
                                            "                color:#787f8d;\n"
                                            "                width:200px;\n"
                                            "                height:35px;\n"
                                            "\n"
                                            "                font-size:20px;\n"
                                            "                font-weight: 700;}\n"
                                            "QPushButton:hover{\n"
                                            "                border-radius:10px;\n"
                                            "                background:#e4e8ec;}\n"
                                            "\n"
                                            "")
        self.left_under_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_under_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_under_frame.setObjectName("left_under_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_under_frame)
        self.verticalLayout.setContentsMargins(33, 0, 33, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.left_under_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.left_label_1 = QtWidgets.QPushButton(self.frame_5)
        self.left_label_1.setEnabled(False)
        self.left_label_1.setStyleSheet("color:#a2a8b2;\n"
                                        "                border:none;\n"
                                        "                font-size:20px;\n"
                                        "                font-weight:700;\n"
                                        "                font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;")
        self.left_label_1.setObjectName("left_label_1")
        self.verticalLayout_4.addWidget(self.left_label_1)
        self.camera_button = QtWidgets.QPushButton(self.frame_5)
        self.camera_button.setStyleSheet("    width: 200px;")
        self.camera_button.setObjectName("camera_button")
        self.camera_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_4.addWidget(self.camera_button)
        self.login_button = QtWidgets.QPushButton(self.frame_5)
        self.login_button.setObjectName("login_button")
        self.login_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_4.addWidget(self.login_button)
        self.logout_button = QtWidgets.QPushButton(self.frame_5)
        self.logout_button.setObjectName("logout_button")
        self.logout_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_4.addWidget(self.logout_button)
        self.register_button = QtWidgets.QPushButton(self.frame_5)
        self.register_button.setObjectName("register_button")
        self.register_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_4.addWidget(self.register_button)
        self.query_user_button = QtWidgets.QPushButton(self.frame_5)
        self.query_user_button.setObjectName("query_user_button")
        self.query_user_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_4.addWidget(self.query_user_button)
        self.left_label_2 = QtWidgets.QPushButton(self.frame_5)
        self.left_label_2.setEnabled(False)
        self.left_label_2.setStyleSheet("color:#a2a8b2;\n"
                                        "                border:none;\n"
                                        "                font-size:20px;\n"
                                        "                font-weight:700;\n"
                                        "                font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;")
        self.left_label_2.setObjectName("left_label_2")
        self.verticalLayout_4.addWidget(self.left_label_2)
        self.recognition_button = QtWidgets.QPushButton(self.frame_5)
        self.recognition_button.setObjectName("recognition_button")
        self.recognition_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_4.addWidget(self.recognition_button)
        self.face_compare_button = QtWidgets.QPushButton(self.frame_5)
        self.face_compare_button.setObjectName("face_compare_button")
        self.face_compare_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.verticalLayout_4.addWidget(self.face_compare_button)
        self.verticalLayout.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.left_under_frame)
        self.horizontalLayout.addWidget(self.left_widget)
        self.right_widget = QtWidgets.QFrame(self.main_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_widget.sizePolicy().hasHeightForWidth())
        self.right_widget.setSizePolicy(sizePolicy)
        self.right_widget.setStyleSheet("#right_widget{\n"
                                        "                background:#f7f9fc;\n"
                                        "                border-top-right-radius:5px;\n"
                                        "                border-bottom-right-radius:5px;}")
        self.right_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_widget.setObjectName("right_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.minimize_button = QtWidgets.QPushButton(self.frame_3)
        self.minimize_button.setGeometry(QtCore.QRect(10, 10, 38, 38))
        self.minimize_button.setStyleSheet("QPushButton{\n"
                                           "                background-color: transparent; \n"
                                           "                border-radius:7px;\n"
                                           "  border: 2px solid #a0a6b1;}\n"
                                           "            QPushButton:hover{\n"
                                           "               padding-top:5px;\n"
                                           "padding-left:5px;\n"
                                           "}")
        # self.minimize_button.setText("")
        self.minimize_button.setObjectName("minimize_button")
        icon_minimize = qtawesome.icon('fa.minus', color='#7b8290')
        self.minimize_button.setIcon(icon_minimize)
        self.minimize_button.setIconSize(QtCore.QSize(30, 30))  # 根据需要调整图标大小
        self.minimize_button.setCursor(QCursor(Qt.PointingHandCursor))

        self.other_button = QtWidgets.QPushButton(self.frame_3)
        self.other_button.setGeometry(QtCore.QRect(70, 10, 38, 38))
        self.other_button.setStyleSheet("QPushButton{\n"
                                        "                background-color: transparent; \n"
                                        "                border-radius:7px;\n"
                                        "  border: 2px solid #a0a6b1;}\n"
                                        "            QPushButton:hover{\n"
                                        "               padding-top:5px;\n"
                                        "padding-left:5px;\n"
                                        "}")
        # self.other_button.setText("")
        self.other_button.setObjectName("other_button")
        icon_other = qtawesome.icon('mdi.window-restore', color='#7b8290')
        self.other_button.setIcon(icon_other)
        self.other_button.setIconSize(QtCore.QSize(30, 30))  # 根据需要调整图标大小
        self.other_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.close_button = QtWidgets.QPushButton(self.frame_3)
        self.close_button.setGeometry(QtCore.QRect(130, 10, 38, 38))
        self.close_button.setStyleSheet("QPushButton{\n"
                                        "                background-color: transparent; \n"
                                        "                border-radius:7px;\n"
                                        "  border: 2px solid #a0a6b1;}\n"
                                        "            QPushButton:hover{\n"
                                        "               padding-top:5px;\n"
                                        "padding-left:5px;\n"
                                        "}")
        self.close_button.setObjectName("close_button")
        # 使用 qtawesome 添加图标
        icon_close = qtawesome.icon('fa.times', color='#7b8290')
        self.close_button.setIcon(icon_close)
        self.close_button.setIconSize(QtCore.QSize(30, 30))  # 根据需要调整图标大小
        self.close_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)
        self.right_frame = QtWidgets.QFrame(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.right_frame.sizePolicy().hasHeightForWidth())
        self.right_frame.setSizePolicy(sizePolicy)
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.camera_label = QtWidgets.QLabel(self.right_frame)
        self.camera_label.setGeometry(QtCore.QRect(70, 20, 900, 560))
        self.camera_label.setMinimumSize(QtCore.QSize(900, 560))
        self.camera_label.setMaximumSize(QtCore.QSize(900, 560))
        self.camera_label.setStyleSheet("color:#787f8d;\n"
                                        "font-size:60px;\n"
                                        "font-weight:bold;\n"
                                        "font-family:Roman times;\n"
                                        "text-text-align: center;")
        self.camera_label.setScaledContents(False)
        self.camera_label.setObjectName("camera_label")
        self.frame_2 = QtWidgets.QFrame(self.right_frame)
        self.frame_2.setGeometry(QtCore.QRect(210, 610, 645, 174))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.msg_label_tittle = QtWidgets.QLabel(self.frame_2)
        self.msg_label_tittle.setMinimumSize(QtCore.QSize(150, 150))
        self.msg_label_tittle.setMaximumSize(QtCore.QSize(150, 150))
        self.msg_label_tittle.setText("")
        self.msg_label_tittle.setObjectName("msg_label_tittle")
        self.horizontalLayout_3.addWidget(self.msg_label_tittle)
        self.msg_label_a = QtWidgets.QLabel(self.frame_2)
        self.msg_label_a.setMinimumSize(QtCore.QSize(150, 150))
        self.msg_label_a.setMaximumSize(QtCore.QSize(150, 150))
        self.msg_label_a.setText("")
        self.msg_label_a.setObjectName("msg_label_a")
        self.horizontalLayout_3.addWidget(self.msg_label_a)
        self.msg_label_b = QtWidgets.QLabel(self.frame_2)
        self.msg_label_b.setMinimumSize(QtCore.QSize(150, 150))
        self.msg_label_b.setMaximumSize(QtCore.QSize(150, 150))
        self.msg_label_b.setText("")
        self.msg_label_b.setObjectName("msg_label_b")
        self.horizontalLayout_3.addWidget(self.msg_label_b)
        self.msg_label_c = QtWidgets.QLabel(self.frame_2)
        self.msg_label_c.setMinimumSize(QtCore.QSize(150, 150))
        self.msg_label_c.setMaximumSize(QtCore.QSize(150, 150))
        self.msg_label_c.setText("")
        self.msg_label_c.setObjectName("msg_label_c")
        self.horizontalLayout_3.addWidget(self.msg_label_c)
        self.verticalLayout_3.addWidget(self.right_frame)
        self.horizontalLayout.addWidget(self.right_widget)
        MainWindow.setCentralWidget(self.main_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # 设置整体样式
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # 隐藏外围边框
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)  # 产生一个无边框的窗口，用户不能移动和改变大小
        MainWindow.setWindowTitle("人脸识别")  # 设置标题
        MainWindow.setWindowIcon(QIcon(':/icons/images/logo.jpg'))  # 设置logo

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "基于人脸识别的\n"
                                                         "图书馆门禁系统"))
        self.pushButton.setText(_translate("MainWindow", "Beta"))
        self.left_label_1.setText(_translate("MainWindow", "Appsettings"))
        self.camera_button.setText(_translate("MainWindow", "打开相机"))
        self.camera_button.setIcon(qtawesome.icon('fa5s.video', color='#787f8d'))

        self.login_button.setText(_translate("MainWindow", "用户登录"))
        self.login_button.setIcon(qtawesome.icon('fa5s.user-alt', color='#787f8d'))

        self.logout_button.setText(_translate("MainWindow", "用户登出"))
        self.logout_button.setIcon(qtawesome.icon('fa5s.sign-out-alt', color='#787f8d'))

        self.register_button.setText(_translate("MainWindow", "用户注册"))
        self.register_button.setIcon(qtawesome.icon('fa.user-plus', color='#787f8d'))

        self.query_user_button.setText(_translate("MainWindow", "修改信息"))
        self.query_user_button.setIcon(qtawesome.icon('fa5s.search', color='#787f8d'))

        self.left_label_2.setText(_translate("MainWindow", "Application"))
        self.recognition_button.setText(_translate("MainWindow", "打开门禁系统"))
        self.recognition_button.setIcon(qtawesome.icon('fa5s.eye', color='#787f8d'))

        self.face_compare_button.setText(_translate("MainWindow", "关于软件"))
        self.face_compare_button.setIcon(qtawesome.icon('fa5s.people-arrows', color='#787f8d'))

        self.camera_label.setText(_translate("MainWindow", "\n\n      欢迎使用学生端v1.0"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    widgets = QtWidgets.QMainWindow()
    ui = UserMainUi()
    ui.setupUi(widgets)
    widgets.show()
    sys.exit(app.exec_())
